In [1]:
pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\hp\anaconda3_2021_11\lib\site-packages (4.0.0-unsupported)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import pyodbc
import pandas as pd
# Some other example server values are
# server = 'localhost\sqlexpress' # for a named instance
# server = 'myserver,port' # to specify an alternate port
server = '127.0.0.1' 
database = 'Finviz' 
username = '' 
password = ''  
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
# select 26 rows from SQL table to insert in dataframe.
queryInsiders = "SELECT * FROM insiders order by ticker;"
df = pd.read_sql(queryInsiders, cnxn)
print(df.head(26))

   iddownload ticker                    date  tradedate          insidername  \
0           1      A 2022-05-09 22:10:29.090 2022-03-18         Tang Michael
1           1      A 2022-05-09 22:10:29.100 2021-12-29       Grau Dominique
2           1      A 2022-05-09 22:10:29.100 2021-12-20  McMullen Michael R.
3           1      A 2022-05-09 22:10:29.100 2021-11-30     Gonsalves Rodney
4           1      A 2022-05-09 22:10:29.100 2021-12-02     Gonsalves Rodney
5           1      A 2022-05-09 22:10:29.100 2021-11-30     Gonsalves Rodney
6           1      A 2022-05-09 22:10:29.103 2021-11-19    McDonnell Padraig
7           1      A 2022-05-09 22:10:29.103 2021-06-10        Thaysen Jacob
8           1      A 2022-05-09 22:10:29.103 2021-05-28    McDonnell Padraig
9           1      A 2022-05-09 22:10:29.103 2021-05-27         Tang Michael
10          1      A 2022-05-09 22:10:29.103 2021-04-23         Tang Michael
11          1      A 2022-05-09 22:10:29.103 2021-04-22  McMullen Michael R.
12          1      A 2022-05-09 22:10:29.103 2021-04-13  McMullen Michael R.
13          1      A 2022-05-09 22:10:29.107 2021-04-08  McMullen Michael R.
14          1      A 2022-05-09 22:10:29.107 2021-03-31      Raha Samraat S.
15          1      A 2022-05-09 22:10:29.107 2021-02-22     Gonsalves Rodney
16          1      A 2022-05-09 22:10:29.107 2021-02-16         Tang Michael
17          1      A 2022-05-09 22:10:29.107 2021-02-16  McMullen Michael R.
18          1      A 2022-05-09 22:10:29.107 2021-02-01  McMullen Michael R.
19          1      A 2022-05-09 22:10:29.107 2021-01-14         Tang Michael
20          1      A 2022-05-09 22:10:29.110 2020-12-01  McMullen Michael R.
21          1      A 2022-05-09 22:10:29.110 2020-11-30        Koh Boon Hwee
22          1      A 2022-05-09 22:10:29.110 2020-11-09         Tang Michael
23          1      A 2022-05-09 22:10:29.110 2020-11-05         Tang Michael
24          1      A 2022-05-09 22:10:29.110 2020-11-03         Tang Michael
25          1      A 2022-05-09 22:10:29.110 2020-10-30         Tang Michael

                       title tradetype   price       value
0             SVP, GC,, Sec.  S - Sale  136.21    164814.0
1                        SVP  S - Sale  161.00    590709.0
2                  CEO, Pres  S - Sale  148.82  18373168.0
3   VP, Corporate Controller  S - Sale  152.04    106274.0
4   VP, Corporate Controller  S - Sale  151.89    121512.0
5   VP, Corporate Controller  S - Sale  152.04    101713.0
6                        SVP  S - Sale  165.00    247500.0
7                        SVP  S - Sale  142.90   2327698.0
8                        SVP  S - Sale  138.42    138420.0
9             SVP, GC,, Sec.  S - Sale  136.15   1833351.0
10            SVP, GC,, Sec.  S - Sale  137.00     68500.0
11                 CEO, Pres  S - Sale  135.00   1222155.0
12                 CEO, Pres  S - Sale  132.50   1187995.0
13                 CEO, Pres  S - Sale  130.26   1966275.0
14                       SVP  S - Sale  127.50    127500.0
15  VP, Corporate Controller  S - Sale  124.17    620850.0
16            SVP, GC,, Sec.  S - Sale  131.16    131155.0
17                 CEO, Pres  S - Sale  130.00   2699580.0
18                 CEO, Pres  S - Sale  122.57   7745187.0
19            SVP, GC,, Sec.  S - Sale  127.27     63635.0
20                 CEO, Pres  S - Sale  115.63   9925910.0
21                       Dir  S - Sale  114.51   2290200.0
22            SVP, GC,, Sec.  S - Sale  116.16    258108.0
23            SVP, GC,, Sec.  S - Sale  111.00    123321.0
24            SVP, GC,, Sec.  S - Sale  107.47    238787.0
25            SVP, GC,, Sec.  S - Sale  102.21    454210.0

In [26]:
queryTickers = "SELECT * FROM findata order by ticker;"
df = pd.read_sql(queryTickers, cnxn)
print(df.head(26))

   iddownload ticker                    date   price  targetprice  \
0           1      A 2022-05-09 22:10:27.567  113.09       159.81
1           1     AA 2022-05-09 22:10:29.507   54.29        91.42
2           1   AAAU 2022-05-09 22:10:30.433   18.41         0.00
3           1    AAC 2022-05-09 22:10:31.157    9.81         0.00
4           1   AACG 2022-05-09 22:10:32.150    1.07        32.00
5           1   AACI 2022-05-09 22:10:32.947    9.86         0.00
6           1   AADI 2022-05-09 22:10:33.690   12.94        48.50
7           1   AADR 2022-05-09 22:10:34.997   51.26         0.00
8           1   AAIC 2022-05-09 22:10:35.850    3.07         4.50
9           1    AAL 2022-05-09 22:10:36.897   16.28        19.26
10          1   AAME 2022-05-09 22:10:38.010    2.98         0.00
11          1    AAN 2022-05-09 22:10:38.883   20.06        27.50
12          1   AAOI 2022-05-09 22:10:40.293    2.21         4.30
13          1   AAON 2022-05-09 22:10:41.747   53.89        71.00
14          1    AAP 2022-05-09 22:10:42.830  202.85       262.50
15          1   AAPL 2022-05-09 22:10:45.120  152.15       190.20
16          1   AAQC 2022-05-09 22:10:46.317    9.78         0.00
17          1    AAT 2022-05-09 22:10:47.023   33.06        38.20
18          1   AATC 2022-05-09 22:10:48.230    6.21         0.00
19          1    AAU 2022-05-09 22:10:49.330    0.28         1.00
20          1   AAWW 2022-05-09 22:10:50.020   69.68        98.86
21          1   AAXJ 2022-05-09 22:10:51.270   66.56         0.00
22          1     AB 2022-05-09 22:10:51.910   38.63        46.00
23          1    ABB 2022-05-09 22:10:53.540   27.92        38.66
24          1   ABBV 2022-05-09 22:10:54.337  150.89       164.73
25          1    ABC 2022-05-09 22:10:55.807  157.35       170.73

         volume  relvolume  rsi14  whigh   wlow  ...  reco  dividendpercent  \
0     1508216.0       0.69  34.30  37.02   2.92  ...   0.0             0.69
1    11303097.0       1.43  25.14  44.65  75.16  ...   2.2             0.66
2      886120.0       0.83  34.28  10.53   7.71  ...   0.0             0.00
3       55856.0       0.20  46.82   0.86   1.55  ...   0.0             0.00
4       25884.0       0.82  32.45  77.47   7.00  ...   1.5             0.00
5        3400.0       0.18  50.91   1.30   5.57  ...   0.0             0.00
6      106097.0       1.10  32.44  74.01   9.55  ...   1.6             0.00
7        9597.0       2.08  31.72  26.10   2.96  ...   0.0             0.32
8       98458.0       1.03  35.34  28.10   0.66  ...   2.7             0.00
9    35375127.0       0.82  37.16  37.48  30.87  ...   2.9             0.00
10        513.0       0.05  44.99  47.63  40.80  ...   0.0             0.67
11     178145.0       0.64  42.64  46.49   9.87  ...   2.6             2.22
12     444200.0       1.33  28.71  76.11   8.67  ...   2.8             0.00
13     229662.0       0.93  54.28  35.68  13.45  ...   2.3             0.73
14     410372.0       0.45  41.37  17.05   8.38  ...   2.2             2.96
15  114913991.0       1.28  37.83  16.83  24.46  ...   1.9             0.58
16      27483.0       0.40  59.26   1.81   1.89  ...   0.0             0.00
17     177431.0       0.61  33.34  19.03   0.63  ...   2.8             3.72
18      23761.0       1.68  38.13  33.65  22.73  ...   0.0             7.58
19     505770.0       0.44  37.36  50.97   6.75  ...   0.0             0.00
20     348311.0       0.51  42.63  28.26  12.15  ...   2.5             0.00
21    1907175.0       1.06  30.51  30.95   2.11  ...   0.0             1.09
22     489309.0       1.10  33.06  32.86   0.12  ...   2.6            12.03
23    2536225.0       0.98  30.90  28.60   2.77  ...   2.0             2.94
24    5539083.0       0.71  41.75  14.22  42.94  ...   2.1             3.69
25    1540517.0       1.20  51.65   5.89  41.32  ...   2.4             1.16

    perfyear  perfhalfyear  employees  optionable  shortable  \
0       9.57         23.20    17200.0         Yes        Yes
1      48.16         31.64    12200.0         Yes        Yes
2       2.52          4.77        0.0          No        Yes
3       0.15          0.00        0.0          No        Yes
4      60.82         51.07      584.0          No        Yes
5       0.00          0.00        0.0          No        Yes
6       7.75         48.53       51.0         Yes        Yes
7      19.52         18.62        0.0          No        Yes
8      24.57         19.48       11.0         Yes        Yes
9      18.91         13.52   123400.0         Yes        Yes
10     25.25         33.41      138.0          No        Yes
11     37.10         19.60     9170.0         Yes        Yes
12     66.62         70.72     2534.0         Yes        Yes
13     21.39         29.54     2881.0         Yes        Yes
14      0.79         11.83    41000.0         Yes        Yes
15     20.79          4.19   154000.0         Yes        Yes
16      0.00          0.41        0.0          No        Yes
17      2.41         10.31      207.0         Yes        Yes
18     14.11          9.57       36.0          No        Yes
19     47.38         22.59        8.0         Yes        Yes
20      4.05         20.64     4056.0         Yes        Yes
21     27.10         20.48        0.0         Yes        Yes
22     10.58         29.83     4118.0         Yes        Yes
23     14.98         16.52   104400.0         Yes        Yes
24     32.03         30.56    50000.0         Yes        Yes
25     31.57         25.42    38000.0         Yes        Yes

                 sector                              industry  country
0           Healthcare                Diagnostics & Research       USA
1      Basic Materials                              Aluminum       USA
2            Financial                  Exchange Traded Fund       USA
3            Financial                       Shell Companies       USA
4   Consumer Defensive         Education & Training Services      Chin
5            Financial                       Shell Companies       USA
6           Healthcare                         Biotechnology       USA
7            Financial                  Exchange Traded Fund       USA
8          Real Estate                       REIT - Mortgage       USA
9          Industrials                              Airlines       USA
10           Financial                      Insurance - Life       USA
11         Industrials             Rental & Leasing Services       USA
12          Technology                        Semiconductors       USA
13         Industrials         Building Products & Equipment       USA
14   Consumer Cyclical                      Specialty Retail       USA
15          Technology                  Consumer Electronics       USA
16           Financial                       Shell Companies       USA
17         Real Estate                    REIT - Diversified       USA
18          Technology    Scientific & Technical Instruments       USA
19     Basic Materials                                  Gold      Cana
20         Industrials               Airports & Air Services       USA
21           Financial                  Exchange Traded Fund       USA
22           Financial                      Asset Management       USA
23         Industrials        Specialty Industrial Machinery      Swit
24          Healthcare          Drug Manufacturers - General       USA
25          Healthcare                  Medical Distribution       USA

[26 rows x 34 columns]

In [27]:
import pandas.io.sql as psql

In [28]:
dfInsiders = pd.read_sql(queryInsiders, cnxn)

In [29]:
dfInsiders

,iddownload,ticker,date,tradedate,insidername,title,tradetype,price,value
0,1,A,2022-05-09 22:10:29.090,2022-03-18,Tang Michael,"SVP, GC,, Sec.",S - Sale,136.21,164814.0
1,1,A,2022-05-09 22:10:29.100,2021-12-29,Grau Dominique,SVP,S - Sale,161.00,590709.0
2,1,A,2022-05-09 22:10:29.100,2021-12-20,McMullen Michael R.,"CEO, Pres",S - Sale,148.82,18373168.0
3,1,A,2022-05-09 22:10:29.100,2021-11-30,Gonsalves Rodney,"VP, Corporate Controller",S - Sale,152.04,106274.0
4,1,A,2022-05-09 22:10:29.100,2021-12-02,Gonsalves Rodney,"VP, Corporate Controller",S - Sale,151.89,121512.0
...,...,...,...,...,...,...,...,...,...
211820,1,VLDR,2022-05-10 00:27:34.913,2021-03-11,Hall Marta Thoma,Dir,S - Sale,12.85,2439291.0
211821,1,VLDR,2022-05-10 00:27:34.913,2021-03-11,Gopalan Anand,"Pres, CEO",S - Sale,12.85,8352041.0
211822,1,VLDR,2022-05-10 00:27:34.917,2021-03-11,Tarman Laura,Vice-Pres of Sales,S - Sale,12.85,42392.0
211823,1,VLDR,2022-05-10 00:27:34.917,2021-03-11,Rekow Mathew,CTO,S - Sale,12.85,1062602.0
211824,1,VLDR,2022-05-10 00:27:34.917,2021-03-11,Jellen Joseph Michael,Chief Strategy Officer,S - Sale,12.85,136741.0

In [30]:
cnxn.close()

In [31]:
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

In [32]:
dfTickers = pd.read_sql(queryTickers, cnxn)

In [33]:
dfTickers

,iddownload,ticker,date,price,targetprice,volume,relvolume,rsi14,whigh,wlow,...,reco,dividendpercent,perfyear,perfhalfyear,employees,optionable,shortable,sector,industry,country
0,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,0.0,0.69,9.57,23.20,17200.0,Yes,Yes,Healthcare,Diagnostics & Research,USA
1,1,AA,2022-05-09 22:10:29.507,54.29,91.42,11303097.0,1.43,25.14,44.65,75.16,...,2.2,0.66,48.16,31.64,12200.0,Yes,Yes,Basic Materials,Aluminum,USA
2,1,AAAU,2022-05-09 22:10:30.433,18.41,0.00,886120.0,0.83,34.28,10.53,7.71,...,0.0,0.00,2.52,4.77,0.0,No,Yes,Financial,Exchange Traded Fund,USA
3,1,AAC,2022-05-09 22:10:31.157,9.81,0.00,55856.0,0.20,46.82,0.86,1.55,...,0.0,0.00,0.15,0.00,0.0,No,Yes,Financial,Shell Companies,USA
4,1,AACG,2022-05-09 22:10:32.150,1.07,32.00,25884.0,0.82,32.45,77.47,7.00,...,1.5,0.00,60.82,51.07,584.0,No,Yes,Consumer Defensive,Education & Training Services,Chin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7686,1,VLCN,2022-05-10 00:27:32.713,1.34,6.00,184319.0,0.45,32.46,92.54,3.88,...,0.0,0.00,0.00,91.83,75.0,No,Yes,Consumer Cyclical,Auto Manufacturers,USA
7687,1,VLD,2022-05-10 00:27:33.473,2.87,10.67,1840788.0,1.89,21.14,78.22,9.46,...,1.7,0.00,71.24,76.53,193.0,Yes,Yes,Technology,Computer Hardware,USA
7688,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,2.7,0.00,85.76,74.49,407.0,Yes,Yes,Technology,Scientific & Technical Instruments,USA
7689,1,VLN,2022-05-10 00:27:35.253,3.18,12.60,87906.0,1.97,21.46,73.91,4.50,...,1.4,0.00,67.88,68.01,263.0,No,Yes,Technology,Semiconductors,Isra
7690,1,VLNS,2022-05-10 00:27:35.923,0.78,0.00,137525.0,0.86,26.26,92.10,5.48,...,0.0,0.00,92.08,81.62,203.0,No,Yes,Healthcare,Drug Manufacturers - Specialty & Generic,Cana

In [34]:
dfFinal = pd.merge(dfTickers, dfInsiders, on=['ticker'])

In [35]:
dfFinal

,iddownload_x,ticker,date_x,price_x,targetprice,volume,relvolume,rsi14,whigh,wlow,...,industry,country,iddownload_y,date_y,tradedate,insidername,title,tradetype,price_y,value
0,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,Diagnostics & Research,USA,1,2022-05-09 22:10:29.090,2022-03-18,Tang Michael,"SVP, GC,, Sec.",S - Sale,136.21,164814.0
1,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,Diagnostics & Research,USA,1,2022-05-09 22:10:29.100,2021-12-29,Grau Dominique,SVP,S - Sale,161.00,590709.0
2,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,Diagnostics & Research,USA,1,2022-05-09 22:10:29.100,2021-12-20,McMullen Michael R.,"CEO, Pres",S - Sale,148.82,18373168.0
3,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,Diagnostics & Research,USA,1,2022-05-09 22:10:29.100,2021-11-30,Gonsalves Rodney,"VP, Corporate Controller",S - Sale,152.04,106274.0
4,1,A,2022-05-09 22:10:27.567,113.09,159.81,1508216.0,0.69,34.30,37.02,2.92,...,Diagnostics & Research,USA,1,2022-05-09 22:10:29.100,2021-12-02,Gonsalves Rodney,"VP, Corporate Controller",S - Sale,151.89,121512.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211820,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,Scientific & Technical Instruments,USA,1,2022-05-10 00:27:34.913,2021-03-11,Hall Marta Thoma,Dir,S - Sale,12.85,2439291.0
211821,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,Scientific & Technical Instruments,USA,1,2022-05-10 00:27:34.913,2021-03-11,Gopalan Anand,"Pres, CEO",S - Sale,12.85,8352041.0
211822,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,Scientific & Technical Instruments,USA,1,2022-05-10 00:27:34.917,2021-03-11,Tarman Laura,Vice-Pres of Sales,S - Sale,12.85,42392.0
211823,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,Scientific & Technical Instruments,USA,1,2022-05-10 00:27:34.917,2021-03-11,Rekow Mathew,CTO,S - Sale,12.85,1062602.0
211824,1,VLDR,2022-05-10 00:27:34.290,1.62,3.62,3173221.0,0.43,30.39,87.33,1.22,...,Scientific & Technical Instruments,USA,1,2022-05-10 00:27:34.917,2021-03-11,Jellen Joseph Michael,Chief Strategy Officer,S - Sale,12.85,136741.0